export const FEATCH_CARS_START = 'FEATCH_CARS_START'
export const FEATCH_CARS_SUCCESS = 'FEATCH_CARS_SUCCESS'
export const FEATCH_CARS_FAILURE = 'FEATCH_CARS_FAILURE'

export const FEATCH_TYPES_START = 'FEATCH_TYPES_START'
export const FEATCH_TYPES_SUCCESS = 'FEATCH_TYPES_SUCCESS'
export const FEATCH_TYPES_FAILURE = 'FEATCH_TYPES_FAILURE'

export const FEATCH_TASKS_START = 'FEATCH_TASKS_START'
export const FEATCH_TASKS_SUCCESS = 'FEATCH_TASKS_SUCCESS'
export const FEATCH_TASKS_FAILURE = 'FEATCH_TASKS_FAILURE'

export const CREATE_TASKS = 'CREATE_TASKS'
